name: afribet   # Nom du projet
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0      # Check for the latest version on pub.dev
  firebase_auth: ^5.3.4       # Check for the latest version on pub.dev
  cloud_firestore: ^5.6.0     # Check for the latest version on pub.dev
  firebase_messaging: ^15.1.6 # Check for the latest version on pub.dev
  flutter_facebook_auth: ^7.1.1 # Check for the latest version on pub.dev
  google_sign_in: ^6.2.2      # Update to the latest version on pub.dev
  flutter_bloc: ^8.0.0
  provider: ^6.0.0
  cached_network_image: ^3.0.0
  intl: ^0.20.1               # Add this line to include the intl package
  http: ^1.2.2
  firebase_data_connect: any  # Utilise la dernière version disponible
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
    - assets/images/
    - assets/videos/