name: Deploy to Firebase Hosting on push 
on: 
  push: 
    branches: 
      - main 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install Firebase CLI 
        run: npm install -g firebase-tools 
      - name: Deploy to Firebase 
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 
        run: firebase deploy --only hosting 
