workflows:
  build_apk:
    name: Build APK

    # Déclenchement des builds sur push
    triggering:
      events:
        - push
      branches:
        only:
          - main

    # Configuration de l'environnement
    environment:
      flutter: stable
      java: 11

    # Etapes du workflow
    scripts:
      - name: Checkout code
        script: |
          git clone $GIT_REPOSITORY_URL .
      - name: Install Node.js
        script: |
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
      - name: Navigate to JS Directory and Install Dependencies
        script: |
          cd docs/public/js
          npm install  # Génération du fichier package-lock.json
          npm ci
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release

    # Définition des artefacts à télécharger
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
